module.exports = {
  userFormateError:{
    code:'10001',
    message:'用户名或密码为空!',
    result:'',
  },
  userExisted:{
    code:'10002',
    message:'用户已经存在!',
    result:'',
  },
  userRegisterError:{
    code:'10003',
    message:'用户注册错误!',
    result:'',
  },
  userDoesNotExist:{
    code:'10004',
    message:'用户不存在!',
    result:'',
  },
  userLoginError:{
    code:'10005',
    message:'用户登录失败！!',
    result:'',
  },
  invalidPassword:{
    code:'10006',
    message:'您输入的密码不正确!',
    result:'',
  }
}